---
template: default.revealjs
metadata-files:
  - templates/document.yaml
metadata:
  revealjs-url: js/vendor/reveal.js
slide-level: 2
from: markdown
to: revealjs
html-math-method:
  method: mathjax
output-file: public/index.html
...
